server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/spring_advanced"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "7Mlh293sSP0wHqIzNuaMmIEVhWh6cWni0ABnPyjFDQ2YAU6vtSMX9KS9aEPY6iD1"